### ISSUE TITLE
url and slider

### ISSUE THREAD

**Issue by cchafe** [ccrma/webchuck-ide#3]
url for sharing .ck files
slider GUI generation
both work separately but not together

[https://chuck.stanford.edu/ide/?url=https://ccrma.stanford.edu/~cc/sonify/HelloSineGUI.ck#](https://chuck.stanford.edu/ide/?url=https://ccrma.stanford.edu/~cc/sonify/HelloSineGUI.ck#)

**Comment by gewang** [comment]
Hi Chris! Discussing this on the chuck dev Discord. From @celestebetancur "we are changing the old generator for the one that I implemented for slork and also, I am waiting for @fenglyfe to have virtual DOM, that way we can avoid the two extra steps generating the GUI" We will keep you posted!

By the way, we'd love to have some kind of "back to school" chuck hackathon before the Fall Quarter, perhaps in late August, to fix bugs and improve things on all fronts for the Fall Quarter (220a, 256a, etc.). Will have more info soon...

**Comment by terryzfeng** [comment]
This is now fixed in #6 ! Thank you Chris for testing it out!

**Comment by terryzfeng** [comment]
Reopening issue after further investigation:
- Bug still occurs ~10% of the time when cold loading a file. 
- p5js seems to be unresponsive in these instances and thus doesn't `setup` and `draw`
- Further p5js framework exploration needed

**Comment by terryzfeng** [comment]
@cchafe Investigated the bug further and found out that p5js doesn't like the asynchronous loading of external files. I've updated the system to handle this. For external URLs, the `Generate UI` button will need to be hit once the file contents are loaded. Let me know if this works!

**Comment by cchafe** [comment]
Looking good, thanks!
Other question: What's the status of safari, ok to use? (I don't have a mac)

**Comment by terryzfeng** [comment]
Yup! Safari is supported and works too (this includes Safari on iOS)
